// Generated by CoffeeScript 1.7.1
(function() {
  var mapping;

  mapping = (function() {
    var store;

    function mapping() {}

    store = Object.create(null);

    mapping.prototype.get = function(key) {
      return store["~" + key];
    };

    mapping.prototype.set = function(key, value) {
      return store["~" + key] = value;
    };

    mapping.prototype["delete"] = function(key) {
      return delete store["~" + key];
    };

    return mapping;

  })();

  module.exports = mapping;

}).call(this);
